---
language: node_js
node_js: 8.5

env:
  global:
    - PERCY_ENABLE=0

sudo: required
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - node_modules

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false
  - npm install -g npm@5
  - npm --version
  - npm install -g greenkeeper-lockfile@1

install:
  - npm install

before_script:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then echo "Enabling Percy on push with default Ember" && export PERCY_ENABLE=1; else export PERCY_ENABLE=0; fi
  - echo $PERCY_ENABLE
  - if [ "$PERCY_ENABLE" -ne 1 ]; then export RANDOMISE=--random; fi
  - echo $RANDOMISE
  - greenkeeper-lockfile-update
  - echo $SPEECH
  - echo $NEWSPEECH
  - echo $XSPEECH
  - echo $LONG_100
  - echo $LONG_200
  - echo $LONG_300
  - echo $LONG_400
  - echo $LONG_500
  - echo $LONG_600
  - echo $LONG_700
  - echo $LONG_800
  - echo $LONG_900
  - echo $LONG_1000
  - echo $LONG_10000
  - echo $LONG_20000
  - echo $LONG_30000
  - echo $LONG_40000
  - echo $LONG_50000
  - echo $LONG_60000
  - echo $LONG_70000
  - echo $LONG_80000

script:
  - npm run lint:js
  - ember exam --reporter dot $RANDOMISE

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - "test $TRAVIS_PULL_REQUEST && test $TRAVIS_PULL_REQUEST != 'false' && $TRAVIS_SECURE_ENV_VARS == 'true' && ./config/deployment/deploy-pull-request.sh"
