---
language: node_js
node_js: 6

env:
  global:
    - PERCY_ENABLE=0
  matrix:
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary

matrix:
  allow_failures:
    - env: EMBER_VERSION=beta
    - env: EMBER_VERSION=canary

  fast_finish: true

sudo: false
dist: trusty

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm config set spin false
  - npm install -g npm@5
  - npm install -g bower
  - bower --version
  - npm --version

install:
  - npm install
  - bower install

before_script:
  - if [ "$EMBER_VERSION" = 'default' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then echo "Enabling Percy on push with default Ember" && export PERCY_ENABLE=1; fi
  - echo $PERCY_ENABLE
  - if [ "$PERCY_ENABLE" -ne 1 ]; then export RANDOMISE=--random; fi
  - echo $RANDOMISE

script:
  - ember try:one $EMBER_VERSION --skip-cleanup=true --- ember exam --reporter dot $RANDOMISE
