---
language: node_js
node_js: 6

env:
  global:
    - PERCY_ENABLE=0
  matrix:
    - EMBER_VERSION=beta
    - EMBER_VERSION=canary

sudo: false
dist: trusty

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm config set spin false
  - npm install -g npm@5
  - npm install -g bower
  - cd && git clone --depth=50 --branch=master https://github.com/travis-ci/travis-web.git travis-ci/travis-web && cd travis-ci/travis-web
  - bower --version
  - npm --version

install:
  - npm install
  - bower install

script:
  - ember try:one $EMBER_VERSION --skip-cleanup=true --- ember exam --reporter dot --random

deploy:
  - provider: script
    skip_cleanup: true
    script: ./config/deployment/deploy-test-master.sh
    on:
      branch: daily-cron
      condition: "$EMBER_VERSION = beta"
  - provider: script
    skip_cleanup: true
    script: ./config/deployment/deploy-test-master.sh
    on:
      branch: daily-cron
      condition: "$EMBER_VERSION = canary"
