---
language: node_js
node_js: 6

sudo: false
dist: trusty

env:
  global:
    - PERCY_ENABLE=0
    - EMBER_SOURCE_TAG=master

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - git clone --depth=50 --branch=master https://github.com/travis-ci/travis-web.git travis-ci/travis-web
  - git clone https://gist.github.com/clekstro/52fc4080904af9dbe944f521b9425ba9.git custom_scripts
  - chmod a+x ./custom-scripts/replace-ember-version.sh
  - ./custom_scripts/replace-ember-version.sh
  - npm config set spin false
  - npm install -g npm@5
  - npm install -g bower
  - bower --version
  - npm --version

install:
  - npm install
  - bower install

script:
  - ember exam --reporter dot --random
