---
language: node_js
node_js: 6

sudo: false
dist: trusty

env:
  global:
    - PERCY_ENABLE=0
    - EMBER_SOURCE_TAG=beta

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - cd && git clone --depth=50 --branch=master https://github.com/travis-ci/travis-web.git travis-ci/travis-web && cd travis-ci/travis-web
  - sed -i "/ember-source/c \"ember-source\": \"emberjs/ember.js#$EMBER_SOURCE_TAG\"" package.json
  - npm config set spin false
  - npm install -g npm@5
  - npm install -g bower
  - bower --version
  - npm --version

install:
  - npm install
  - bower install

script:
  - ember exam --reporter dot --random
